In [8]:
using LinearAlgebra

# Questão 01

<img src="Q1.jpg" width="300">

In [9]:
# Passo 0
A = [4 8 1 ; 0 2 -2 ; 3 6 7];

n = size(A,1);

In [10]:
# Passo 1
A1 = A;

x = A1[:,1];
e1 = zeros(n); e1[1] = 1;

α1 = norm(x);
v = x - α1*e1;
u = v / norm(v);
Q1 = diagm(ones(n)) - 2*u*u'

3×3 Matrix{Float64}:
 0.8  0.0   0.6
 0.0  1.0   0.0
 0.6  0.0  -0.8

In [11]:
# Passo 2
A2 = Q1*A1;
A2til = A2[2:end,2:end]

2×2 Matrix{Float64}:
 2.0          -2.0
 8.88178e-16  -5.0

In [12]:
# n - 1 = 2
# k = 2
# Repita os passos 1 e 2 para A2til
# Passo 1
x = A2til[:,1];
e1 = zeros(n-1); e1[1] = 1;

α2 = norm(x);
v = x - α2*e1;
u = v / norm(v);
Q2til = diagm(ones(n-1)) - 2*u*u'
Q2 = [1 zeros(1,n-1) ; zeros(n-1,1) Q2til]

3×3 Matrix{Float64}:
 1.0  0.0   0.0
 0.0  1.0   0.0
 0.0  0.0  -1.0

In [13]:
# Determinando A3 e A3til
# Passo 2
A3 = Q2*A2
A3til = A3[3:end,3:end]

1×1 Matrix{Float64}:
 4.999999999999999

In [17]:
Q = Q1*Q2
R = A3

Q * R

3×3 Matrix{Float64}:
 4.0  8.0   1.0
 0.0  2.0  -2.0
 3.0  6.0   7.0

# Questão 02

<img src="Q2.jpg" width="300">

In [19]:
include("GS_MOD.jl");

In [21]:
A = [4 8 ; 0 2 ; 3 6];

Q, R = GS_MOD_LOG(A)

Q * R

Para k = 1 2 faça
	u1 = A[:, 1] => 

[4, 0, 3]
	u2 = A[:, 2] => [8, 2, 6]
	Para k = 1 faça:
		r[1, 1] = norm(u1) => 

5.0


		w1 = u1/r[1, 1] => 

[0.8, 0.0, 0.6]
		Para j = 2 faça:
			R[1, 2] = w1'*u2 => 10.0
			u2 = u2 - R[1, 2]*w1 => [0.0, 2.0, 0.0]

	Para k = 2 faça:
		r[2, 2] = norm(u2) => 2.0
		w2 = u2/r[2, 2] => [0.0, 1.0, 0.0]



3×2 Matrix{Float64}:
 4.0  8.0
 0.0  2.0
 3.0  6.0

# Questão 03

<img src="Q3.jpg" width="300">

In [22]:
A = [1 1 0 ; -1 1 0 ; 0 0 -1];
b = [1 ; 1 ; 1];

Q, R = GS_MOD_LOG(A)

Q * R

Para k = 1 2 3 faça
	u1 = A[:, 1] => [1, -1, 0]
	u2 = A[:, 2] => [1, 1, 0]
	u3 = A[:, 3] => [0, 0, -1]
	Para k = 1 faça:
		r[1, 1] = norm(u1) => 1.41421
		w1 = u1/r[1, 1] => [0.70711, -0.70711, 0.0]
		Para j = 2 faça:
			R[1, 2] = w1'*u2 => 0.0
			u2 = u2 - R[1, 2]*w1 => [1.0, 1.0, 0.0]
		Para j = 3 faça:
			R[1, 3] = w1'*u3 => 0.0
			u3 = u3 - R[1, 3]*w1 => [0.0, 0.0, -1.0]

	Para k = 2 faça:
		r[2, 2] = norm(u2) => 1.41421
		w2 = u2/r[2, 2] => [0.70711, 0.70711, 0.0]
		Para j = 3 faça:
			R[2, 3] = w2'*u3 => 0.0
			u3 = u3 - R[2, 3]*w2 => [0.0, 0.0, -1.0]

	Para k = 3 faça:
		r[3, 3] = norm(u3) => 1.0
		w3 = u3/r[3, 3] => [0.0, 0.0, -1.0]



3×3 Matrix{Float64}:
  1.0  1.0   0.0
 -1.0  1.0   0.0
  0.0  0.0  -1.0

In [24]:
y = Q'*b;
x = R\y # solução do sistema
x = round.(x, digits=3)

3-element Vector{Float64}:
  0.0
  1.0
 -1.0

# Questão 04

<img src="Q4.jpg" width="300">

In [30]:
function MinQuad(A, b)
    Q, R = GS_MOD(A);
    bch = Q'*b
    bch = round.(bch; digits=5)
    x = R\bch
    x = round.(x; digits=2)
    return x
end

MinQuad (generic function with 1 method)

In [31]:
A = [2 0 ; -1 0 ; 0 -1];
b = [1 ; 1 ; 1]

x = MinQuad(A, b)

println("\nx = ", x)
println("\né o vetor de R³ que minimiza o (PMQ)\ncom valor mínimo de ", norm(A*x - b)^2)


x = [0.2, -1.0]

é o vetor de R³ que minimiza o (PMQ)
com valor mínimo de 1.8
