In [2]:
using LinearAlgebra

# Questão 01

Seja
$$
A = \begin{bmatrix}
 4 & 8 & 1\\
 0 & 2 & -2\\
 3 & 6 & 7
\end{bmatrix} \in \mathbb{R}^{3 \times 3}
$$
Desta forma:

1. Determine a Decomposição $QR$ da matriz $A$, na forma $A = QR$.
Usando o Algoritmo de Householder.

In [3]:
# Passo 0
A = [4 8 1 ; 0 2 -2 ; 3 6 7];

n = size(A,1);

In [4]:
# Passo 1
A1 = A;

x = A1[:,1];
e1 = zeros(n); e1[1] = 1;

α1 = norm(x); # i
v = x - α1*e1; # ii
u = v / norm(v); # iii
Q1 = diagm(ones(n)) - 2*u*u' # iv Q_1 = I_n - 2uu^T

print("\nx = A1(:,1) = ", x, "\n")
print("\ne1 = ", e1, "\n")
print("\nα1 = ", α1, "\n")
print("\nv = x - α1*e1 = ", v, "\n")
print("\nu = v / norm(v) = ", round.((u) ; digits=5), "\n")
print("\nQ_1 = I_n - 2uu^T = ", round.((Q1); digits=5), "\n")


x = A1(:,1) = 

[4, 0, 3]



e1 = 

[1.0, 0.0, 0.0]

α1 = 5.0

v = x - α1*e1 = [-1.0, 0.0, 3.0]



u = v / norm(v) = [-0.31623, 0.0, 0.94868]



Q_1 = I_n - 2uu^T = 

[0.8 0.0 0.6; 0.0 1.0 0.0; 0.6 0.0 -0.8]


In [5]:
# TESTES
# round.((round(sqrt(2)) * u) ; digits=5)
# t = sqrt(2) * [-1/2 ; 2/5 ; 3/10]
# 2*(t * t')
# diagm(ones(n)) - 2*u*u'

In [6]:
# Passo 2
A2 = Q1*A1
A2til = A2[2:end,2:end]

# A2[1,1] == α1;

2×2 Matrix{Float64}:
 2.0          -2.0
 8.88178e-16  -5.0

In [7]:
# n - 1 = 2
# k = 2
# Repita os passos 1 e 2 para A2til
# Passo 1
x = A2til[:,1];
e1 = zeros(n-1); e1[1] = 1;

α2 = norm(x);
v = x - α2*e1;
u = v / norm(v);
Q2til = diagm(ones(n-1)) - 2*u*u'
Q2 = [1 zeros(1,n-1) ; zeros(n-1,1) Q2til]

print("\nx = A2til(:,1) = ", round.((x) ; digits = 5), "\n")
print("\ne1 = ", e1, "\n")
print("\nα2 = ", α2, "\n")
print("\nv = x - α2*e1 = ", round.((v) ; digits = 5), "\n")
print("\nu = v / norm(v) = ", round.((u) ; digits=5), "\n")
print("\nQ_2til = I_n-1 - 2uu^T = ", round.((Q2til); digits=5), "\n")
print("\nQ_2 = ", round.((Q2); digits=5), "\n")


x = A2til(:,1) = [2.0, 0.0]

e1 = [1.0, 0.0]

α2 = 2.0

v = x - α2*e1 = [0.0, 0.0]

u = v / norm(v) = [0.0, 1.0]

Q_2til = I_n-1 - 2uu^T = [1.0 0.0; 0.0 -1.0]

Q_2 = [1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 -1.0]


In [8]:
# TESTES
# round.((round(sqrt(2)) * u) ; digits=5)

# round.(([4/5 3/5 ; 3/5 -4/5]) ; digits=5) == round.((Q2til) ; digits=5) # minhas contas tão certas

In [9]:
# Determinando A3 e A3til
# Passo 2
A3 = Q2*A2
A3til = A3[3:end,3:end]

1×1 Matrix{Float64}:
 4.999999999999999

In [10]:
Q = Q1*Q2
R = A3

Q * R

3×3 Matrix{Float64}:
 4.0  8.0   1.0
 0.0  2.0  -2.0
 3.0  6.0   7.0

# Questão 02

Seja
$$
A = \begin{bmatrix}
 4 & 8 \\
 0 & 2 \\
 3 & 6 
\end{bmatrix} \in \mathbb{R}^{3 \times 2}
$$
Desta forma:

1. Determine a Decomposição $QR$ Reduzida da matriz $A$, na forma $A = QR$.
Usando o Algoritmo de GS Modificado.

In [11]:
include("GS_MOD.jl");

In [12]:
A = [4 8 ; 0 2 ; 3 6];

Q, R = GS_MOD_LOG(A)

Q * R

Algoritmo de Gram-Schmidt MODIFICADO
Para k = 1 2 faça
	u1 = A[:, 1] => [4, 0, 3]
	u2 = A[:, 2] => [8, 2, 6]
	Para k = 1 faça:
		r[1, 1] = norm(u1) => 5.0


		w1 = u1/r[1, 1] => [0.8, 0.0, 0.6]
		Para j = 2 faça:
			R[1, 2] = w1'*u2 => 10.0
			u2 = u2 - R[1, 2]*w1 => [0.0, 2.0, 0.0]

	Para k = 2 faça:
		r[2, 2] = norm(u2) => 2.0
		w2 = u2/r[2, 2] => [0.0, 1.0, 0.0]



3×2 Matrix{Float64}:
 4.0  8.0
 0.0  2.0
 3.0  6.0

# Questão 03

Seja o sistema linear $Ax = b$, onde
$$
A = \begin{bmatrix}
 1 & 1 & 0\\
 -1 & 1 & 0\\
 0 & 0 & -1
\end{bmatrix} \in \mathbb{R}^{3 \times 3}
$$
e
$$
b = \begin{bmatrix}
 1\\
 1\\
 1
\end{bmatrix} \in \mathbb{R}^{3 \times 1}
$$
Desta forma:

1. Calcule a fatoração $QR$ da matriz $A$, isto é $A = QR$.
2. Resolva o sistema linear $Ax = b$, usando a fatoração $QR$ da matriz $A$.

In [13]:
A = [1 1 0 ; -1 1 0; 0 0 -1];
b = [1 ; 1 ; 1];

Q, R = GS_MOD_LOG(A)

R

Algoritmo de Gram-Schmidt MODIFICADO
Para k = 1 2 3 faça
	u1 = A[:, 1] => [1, -1, 0]
	u2 = A[:, 2] => [1, 1, 0]
	u3 = A[:, 3] => [0, 0, -1]
	Para k = 1 faça:
		r[1, 1] = norm(u1) => 1.41421
		w1 = u1/r[1, 1] => [0.70711, -0.70711, 0.0]
		Para j = 2 faça:
			R[1, 2] = w1'*u2 => 0.0
			u2 = u2 - R[1, 2]*w1 => [1.0, 1.0, 0.0]
		Para j = 3 faça:
			R[1, 3] = w1'*u3 => 0.0
			u3 = u3 - R[1, 3]*w1 => [0.0, 0.0, -1.0]

	Para k = 2 faça:
		r[2, 2] = norm(u2) => 1.41421
		w2 = u2/r[2, 2] => [0.70711, 0.70711, 0.0]
		Para j = 3 faça:
			R[2, 3] = w2'*u3 => 0.0
			u3 = u3 - R[2, 3]*w2 => [0.0, 0.0, -1.0]

	Para k = 3 faça:
		r[3, 3] = norm(u3) => 1.0
		w3 = u3/r[3, 3] => [0.0, 0.0, -1.0]



3×3 Matrix{Float64}:
 1.41421  0.0      0.0
 0.0      1.41421  0.0
 0.0      0.0      1.0

In [14]:
y = Q'*b;
x = R\y # solução do sistema
x = round.(x, digits=3)
# round((y[1]) ; digits= 5) == round((sqrt(2)) ; digits = 5)

3-element Vector{Float64}:
  0.0
  1.0
 -1.0

# Questão 04

Seja o sistema linear $Ax = b$, onde
$$
A = \begin{bmatrix}
 2 & 0\\
 -1 & 0\\
 0 & -1
\end{bmatrix} \in \mathbb{R}^{3 \times 2}
$$
e
$$
b = \begin{bmatrix}
 1\\
 1\\
 1
\end{bmatrix} \in \mathbb{R}^{3 \times 1}
$$
Desta forma:

1. Resolva o sistema linear $Ax = b$, usando o Algoritmo $PMQ$ via fatoração $QR$ da matriz $A$.

In [15]:
include("GS_MOD.jl")

GS_MOD_LOG (generic function with 1 method)

In [16]:
function MinQuad(A, b)
    m, n = size(A)
    Q, R = GS_MOD_LOG(A);
    print("\nQ = ", round.(Q; digits=5), "\n")
    print("\nR = ", round.(R; digits=5), "\n")
    bch = Q'*b
    print("\nQ^T = ", round.(Q'; digits=5), "\n")
    bch = round.(bch; digits=5)
    print("\nbch = ", bch, "\n")
    x = R\bch
    x = round.(x; digits=2)
    if n == rank(A)
        # n == posto(A) / A tem posto completo
        println("Sistema tem solução única") # tem n colunas LI
    end
    return x
end

MinQuad (generic function with 1 method)

In [17]:
A = [1 0 ; -1 0 ; 0 1];
b = [1 ; 1 ; 1]

x = MinQuad(A, b)
n = size(x, 1)

print("\nx = ", x)
println("\né o vetor de R$n que minimiza o (PMQ)\ncom valor mínimo de ", round((norm(A*x - b)^2) ; digits = 5))

Algoritmo de Gram-Schmidt MODIFICADO
Para k = 1 2 faça
	u1 = A[:, 1] => [1, -1, 0]
	u2 = A[:, 2] => [0, 0, 1]
	Para k = 1 faça:
		r[1, 1] = norm(u1) => 1.41421
		w1 = u1/r[1, 1] => [0.70711, -0.70711, 0.0]
		Para j = 2 faça:
			R[1, 2] = w1'*u2 => 0.0
			u2 = u2 - R[1, 2]*w1 => [0.0, 0.0, 1.0]

	Para k = 2 faça:
		r[2, 2] = norm(u2) => 1.0
		w2 = u2/r[2, 2] => [0.0, 0.0, 1.0]


Q = [0.70711 0.0; -0.70711 0.0; 0.0 1.0]

R = [1.41421 0.0; 0.0 1.0]

Q^T = [0.70711 -0.70711 0.0; 0.0 0.0 1.0]

bch = [0.0, 1.0]
Sistema tem solução única

x = [0.0, 1.0]


é o vetor de R2 que minimiza o (PMQ)
com valor mínimo de 2.0
