In [1]:
using LinearAlgebra

In [2]:
function GS_MOD(A)
    m, n = size(A)
    Q = zeros(m, n)
    R = zeros(n, n)
    for j = 1:n
        v = A[:, j]
        for i = 1:j-1
            R[i, j] = dot(Q[:, i], A[:, j])
            v = v - R[i, j]*Q[:, i]
        end
        R[j, j] = norm(v)
        Q[:, j] = v/R[j, j]
    end
    return Q, R
end

GS_MOD (generic function with 1 method)

In [4]:
A = [12 -51 4 ; 5 167 -68 ; -4 24 -41]

3×3 Matrix{Int64}:
 12  -51    4
  5  167  -68
 -4   24  -41

In [6]:
Q, R = GS_MOD(A)

Q * R

3×3 Matrix{Float64}:
 12.0  -51.0    4.0
  5.0  167.0  -68.0
 -4.0   24.0  -41.0

In [8]:
B = [2 1 -3 ; -2 0 -2 ; -1 2 1]

Q, R = GS_MOD(B)

Q * R

3×3 Matrix{Float64}:
  2.0  1.0  -3.0
 -2.0  0.0  -2.0
 -1.0  2.0   1.0