In [2]:
using LinearAlgebra

In [89]:
function GS_MOD(A)
    m, n = size(A)
    Q = zeros(m, n)
    R = zeros(n, n)

    kValues = []
    print("Para k = ")
    for k = 1:n
        print(k, " ")
    end

    print("faça\n")


    for k = 1:n
        print("\tPara k = $k faça:\n")
        v = A[:, k]
        print("\t\tu$k = A(:, $k) => ", v, "\n")
        for j = 1:k-1
            print("\t\tPara j = $j faça:\n")
            print("\t\t\tR[$j, $k] = w$j'*u$k => ", dot(Q[:, j], A[:, k]), "\n")
            R[j, k] = dot(Q[:, j], A[:, k])
            print("\t\t\tu$k = u$k - R[$j, $k]*w$j => ", v - R[j, k]*Q[:, j], "\n")
            v = v - R[j, k]*Q[:, j]
        end
        print("\t\tr[$k, $k] = norm(u$k) => ", norm(v), "\n")
        print("\t\tw$k = u$k/r[$k, $k] => ", v/norm(v), "\n") # Q[:, k] = v/R[k, k
        R[k, k] = norm(v)
        Q[:, k] = v/R[k, k]
        print("\n")
    end
    return Q, R
end

GS_MOD (generic function with 1 method)

In [90]:
A = [4 5 ; 3 5 ; 0 -1/2];

Q, R = GS_MOD(A);

# println("Q = ", Q)
# println("R = ", R)
Q * R

Para k = 1 2 faça
	Para k = 1 faça:
		u1 = A(:, 1) => [4.0, 3.0, 0.0]
		r[1, 1] = norm(u1) => 5.0
		w1 = u1/r[1, 1] => [0.8, 0.6, 0.0]

	Para k = 2 faça:
		u2 = A(:, 2) => [5.0, 5.0, -0.5]
		Para j = 1 faça:
			R[1, 2] = w1'*u2 => 7.0
			u2 = u2 - R[1, 2]*w1 => [-0.6000000000000005, 0.7999999999999998, -0.5]
		r[2, 2] = norm(u2) => 1.1180339887498951
		w2 = u2/r[2, 2] => [-0.5366563145999499, 0.7155417527999324, -0.4472135954999578]



3×2 Matrix{Float64}:
 4.0   5.0
 3.0   5.0
 0.0  -0.5

In [91]:
A = [1 -2 1 ; 2 -1 0 ; 1 -1 1 ; -1 0 2];

Q, R = GS_MOD(A);

Q * R

Para k = 1 2 3 faça
	Para k = 1 faça:
		u1 = A(:, 1) => [1, 2, 1, -1]
		r[1, 1] = norm(u1) => 2.6457513110645907
		w1 = u1/r[1, 1] => [0.3779644730092272, 0.7559289460184544, 0.3779644730092272, -0.3779644730092272]

	Para k = 2 faça:
		u2 = A(:, 2) => [-2, -1, -1, 0]
		Para j = 1 faça:
			R[1, 2] = w1'*u2 => -1.889822365046136
			u2 = u2 - R[1, 2]*w1 => [-1.2857142857142858, 0.4285714285714284, -0.2857142857142858, -0.7142857142857142]
		r[2, 2] = norm(u2) => 1.5583874449479593
		w2 = u2/r[2, 2] => [-0.8250286473253902, 0.27500954910846326, -0.1833396994056423, -0.4583492485141055]

	Para k = 3 faça:
		u3 = A(:, 3) => [1, 0, 1, 2]
		Para j = 1 faça:
			R[1, 3] = w1'*u3 => 0.0
			u3 = u3 - R[1, 3]*w1 => [1.0, 0.0, 1.0, 2.0]
		Para j = 2 faça:
			R[2, 3] = w2'*u3 => -1.9250668437592435
			u3 = u3 - R[2, 3]*w2 => [-0.588235294117647, 0.529411764705882, 0.6470588235294117, 1.1176470588235299]
		r[3, 3] = norm(u3) => 1.5146344928922042
		w3 = u3/r[3, 3] => [-0.3883678186903085, 0.349531036

4×3 Matrix{Float64}:
  1.0  -2.0           1.0
  2.0  -1.0          -1.53522e-17
  1.0  -1.0           1.0
 -1.0   3.91257e-17   2.0

In [92]:
A = [12 -51 4 ; 5 167 -68 ; -4 24 -41]
Q, R = GS_MOD(A)

Q * R

Para k = 1 2 3 faça
	Para k = 1 faça:
		u1 = A(:, 1) => [12, 5, -4]
		r[1, 1] = norm(u1) => 13.601470508735444
		w1 = u1/r[1, 1] => [0.8822575465125693, 0.36760731104690386, -0.2940858488375231]

	Para k = 2 faça:
		u2 = A(:, 2) => [-51, 167, 24]
		Para j = 1 faça:
			R[1, 2] = w1'*u2 => 9.337225700591363
			u2 = u2 - R[1, 2]*w1 => [-59.237837837837844, 163.56756756756758, 26.745945945945948]
		r[2, 2] = norm(u2) => 176.00800043241279
		w2 = u2/r[2, 2] => [-0.33656332491877394, 0.9293189353081576, 0.1519586943788752]

	Para k = 3 faça:
		u3 = A(:, 3) => [4, -68, -41]
		Para j = 1 faça:
			R[1, 3] = w1'*u3 => -9.410747162800739
			u3 = u3 - R[1, 3]*w1 => [12.302702702702701, -64.54054054054055, -43.76756756756757]
		Para j = 2 faça:
			R[2, 3] = w2'*u3 => -70.7702473701637
			u3 = u3 - R[2, 3]*w2 => [-11.515967057523712, 1.227590396994927, -33.01341317632747]
		r[3, 3] = norm(u3) => 34.98585321245828
		w3 = u3/r[3, 3] => [-0.32916067496169954, 0.03508819377764348, -0.943621782663044]



3×3 Matrix{Float64}:
 12.0  -51.0    4.0
  5.0  167.0  -68.0
 -4.0   24.0  -41.0

In [93]:
B = [2 1 -3 ; -2 0 -2 ; -1 2 1]

Q, R = GS_MOD(B)

Q * R

Para k = 1 2 3 faça
	Para k = 1 faça:
		u1 = A(:, 1) => [2, -2, -1]
		r[1, 1] = norm(u1) => 3.0
		w1 = u1/r[1, 1] => [0.6666666666666666, -0.6666666666666666, -0.3333333333333333]

	Para k = 2 faça:
		u2 = A(:, 2) => [1, 0, 2]
		Para j = 1 faça:
			R[1, 2] = w1'*u2 => 0.0
			u2 = u2 - R[1, 2]*w1 => [1.0, 0.0, 2.0]
		r[2, 2] = norm(u2) => 2.23606797749979
		w2 = u2/r[2, 2] => [0.4472135954999579, 0.0, 0.8944271909999159]

	Para k = 3 faça:
		u3 = A(:, 3) => [-3, -2, 1]
		Para j = 1 faça:
			R[1, 3] = w1'*u3 => -1.0
			u3 = u3 - R[1, 3]*w1 => [-2.3333333333333335, -2.6666666666666665, 0.6666666666666667]
		Para j = 2 faça:
			R[2, 3] = w2'*u3 => -0.447213595499958
			u3 = u3 - R[2, 3]*w2 => [-2.1333333333333333, -2.6666666666666665, 1.0666666666666669]
		r[3, 3] = norm(u3) => 3.5777087639996634
		w3 = u3/r[3, 3] => [-0.5962847939999439, -0.7453559924999299, 0.298142396999972]



3×3 Matrix{Float64}:
  2.0  1.0  -3.0
 -2.0  0.0  -2.0
 -1.0  2.0   1.0