In [9]:
using LinearAlgebra

In [66]:
# Algoritmo QR manual

A = [4 1 ; 5 3]
U = zeros(2, 2)

U[:, 1] = A[:, 1] / norm(A[:, 1])

U[:, 2] = (A[:, 2] - dot(U[:, 1], A[:, 2]) * U[:, 1])
U[:, 2] = U[:, 2] / norm(U[:, 2])

Q = U
R = Q' * A

Q*R # igual a A

2×2 Matrix{Float64}:
 4.0  1.0
 5.0  3.0

In [39]:
function GS(A)
    n, k = size(A)
    U = zeros(n, k)
    U[:, 1] = A[:, 1] / norm(A[:, 1])

    for i = 2:k
        U[:, i] = A[:, i]
        for j = 1:i-1
            U[:, i] -= (U[:, j]' * A[:, i]) * U[:, j]
        end
        U[:, i] /= norm(U[:, i])
    end

    return U
end

GS (generic function with 1 method)

In [17]:
function gram_schmidt(a; tol = 1e-10)
    
    q = []           # inicializamos o array de saida como um array vazio
    for i = 1:length(a)
        qtilde = a[i]
        for j = 1:i-1
            qtilde -= (q[j]'*a[i]) * q[j]
        end
        if norm(qtilde) < tol
            println("Os vetores são linearmente dependentes.")
            return q
        end
        push!(q, qtilde/norm(qtilde))    #Em cada iteração, adicionamos o seguinte vetor ao array usando a função push!
        end;
    return q
end

gram_schmidt (generic function with 1 method)

In [10]:
function proj(u, v)
    return (dot(u, v) / dot(u, u)) * u
end

proj (generic function with 1 method)

In [11]:
v = [4 ; 5];
u = [1 ; 3];

In [15]:
proj(u, v) # v sobre u

2-element Vector{Float64}:
 1.9
 5.699999999999999

In [43]:
proj(v, u) # u sobre v

2-element Vector{Float64}:
 1.853658536585366
 2.3170731707317076

In [69]:
A = [1 1 2 ; 0 0 1; 1 0 0]

println(det(A) != 0)
GS(A) * (GS(A)' * A) # Q * R

true


3×3 Matrix{Float64}:
 1.0   1.0           2.0
 0.0  -2.22045e-16   1.0
 1.0  -1.11022e-16  -9.86076e-32

In [70]:
B = [25 276/25 232/25 ; 95 146 72 ; -10 6 -33]

println(det(B) != 0)
GS(B) * (GS(B)' * B) # Q * R

true


3×3 Matrix{Float64}:
  25.0   11.04    9.28
  95.0  146.0    72.0
 -10.0    6.0   -33.0

In [72]:
GS(B)' * B

3×3 Matrix{Float64}:
 98.7421       142.654       74.963
 -1.33227e-13   33.5199      -8.27422
 -1.19904e-13   -4.9738e-14  25.9077