In [1]:
using LinearAlgebra

In [2]:
function qrfact(A)
    m,n = size(A)
    Qt = diagm(ones(m))
    R = float(copy(A))
    for k in 1:n
        z = R[k:m,k]
        w = [ -sign(z[1])*norm(z) - z[1]; -z[2:end] ]
        nrmw = norm(w)
        if nrmw < eps() continue; end    # skip this iteration
        v = w / nrmw;
        # Apply the reflection to each relevant column of A and Q
        for j in 1:n
            R[k:m,j] -= v*( 2*(v'*R[k:m,j]) )
        end
        for j in 1:m
            Qt[k:m,j] -= v*( 2*(v'*Qt[k:m,j]) )
        end
    end
    return Qt',triu(R)
end

qrfact (generic function with 1 method)

In [3]:
A = [12 -51 4 ; 6 167 -68 ; -4 24 -41]

# Q, R = HouseHolder(A)

Q, R = qrfact(A)

Q * R

3×3 Matrix{Float64}:
 12.0  -51.0    4.0
  6.0  167.0  -68.0
 -4.0   24.0  -41.0

In [4]:
A = [4 5 ; 3 5; 0 -1/2];

Q, R = qrfact(A)

Q

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 -0.8   0.536656  -0.268328
 -0.6  -0.715542   0.357771
  0.0   0.447214   0.894427

# QR Reduzido Manual

In [12]:
A1 = A;

x = A1[:,1]
e1 = [1 ; 0 ; 0];
α1 = norm(x)
v = x - α1*e1;

u = v / norm(v)

Q1 = diagm(ones(3)) - 2*u*u'

3×3 Matrix{Float64}:
 0.8   0.6  0.0
 0.6  -0.8  0.0
 0.0   0.0  1.0

In [17]:
A2 = Q1*A1
A2til = A2[2:end,2:end]

2×1 Matrix{Float64}:
 -0.9999999999999991
 -0.5

In [23]:
x = A2til[:,1]
e1 = [1 ; 0];

α2 = norm(x)
v = x - α2*e1;
u = v / norm(v)

Q2til = diagm(ones(2)) - 2*u*u'
Q2 = [1 0 0 ; 0 Q2til[1,1] Q2til[1,2] ; 0 Q2til[2,1] Q2til[2,2]]

3×3 Matrix{Float64}:
 1.0   0.0        0.0
 0.0  -0.894427  -0.447214
 0.0  -0.447214   0.894427

In [25]:
A3 = Q2*A2

3×2 Matrix{Float64}:
  5.0          7.0
 -3.97205e-16  1.11803
 -1.98603e-16  0.0

In [27]:
R = A3
Q = Q1*Q2

Q * R

3×2 Matrix{Float64}:
  4.0           5.0
  3.0           5.0
 -4.18842e-32  -0.5

In [32]:
Qch = [Q[:,1] Q[:,2]]

3×2 Matrix{Float64}:
 0.8  -0.536656
 0.6   0.715542
 0.0  -0.447214

MethodError: MethodError: no method matching diagm(::Matrix{Int64})

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.

Closest candidates are:
  diagm(!Matched::Integer, !Matched::Integer, !Matched::Pair{<:Integer, <:AbstractVector}...)
   @ LinearAlgebra ~/bin/julia-1.9.3/share/julia/stdlib/v1.9/LinearAlgebra/src/dense.jl:292
  diagm(!Matched::AbstractVector)
   @ LinearAlgebra ~/bin/julia-1.9.3/share/julia/stdlib/v1.9/LinearAlgebra/src/dense.jl:341
  diagm(!Matched::Integer, !Matched::Integer, !Matched::AbstractVector)
   @ LinearAlgebra ~/bin/julia-1.9.3/share/julia/stdlib/v1.9/LinearAlgebra/src/dense.jl:342
  ...
