In [62]:
using LinearAlgebra
using Printf

In [77]:
function GS_MOD(A)
    m, n = size(A)
    Q = zeros(m, n)
    R = zeros(n, n)

    u = []
    for i = 1:n
        push!(u, A[:, i])
    end
    for k = 1:n
        R[k, k] = norm(u[k])
        Q[:, k] = u[k]/R[k, k]
        for j = k+1:n
            R[k, j] = dot(Q[:, k], u[j])
            u[j] = u[j] - R[k, j]*Q[:, k]
        end
    end
    return Q, R
end

GS_MOD (generic function with 1 method)

In [78]:
function GS_MOD_LOG(A)
    m, n = size(A)
    Q = zeros(m, n)
    R = zeros(n, n)

    kValues = []
    print("Para k = ")
    for k = 1:n
        print(k, " ")
    end

    print("faça\n")

    u = []
    for i = 1:n
        push!(u, A[:, i])
        print("\tu$i = A[:, $i] => ", u[i], "\n")
    end


    for k = 1:n
        print("\tPara k = $k faça:\n")
        # v = u[k]
        # print("\t\tu$k = A(:, $k) => ", v, "\n")
        print("\t\tr[$k, $k] = norm(u$k) => ", norm(u[k]), "\n")
        print("\t\tw$k = u$k/r[$k, $k] => ", u[k]/norm(u[k]), "\n") # Q[:, k] = v/R[k, k
        R[k, k] = norm(u[k])
        Q[:, k] = u[k]/R[k, k]
        for j = k+1:n
            print("\t\tPara j = $j faça:\n")
            print("\t\t\tR[$k, $j] = w$k'*u$j => ", dot(Q[:, k], u[j]), "\n")
            R[k, j] = dot(Q[:, k], u[j])
            print("\t\t\tu$j = u$j - R[$k, $j]*w$k => ", u[j] - R[k, j]*Q[:, k], "\n")
            # v = A[:, j] - R[k, j]*Q[:, k]
            # v = v - R[k, j]*Q[:, k]
            u[j] = u[j] - R[k, j]*Q[:, k]
        end
        print("\n")
    end
    return Q, R
end

GS_MOD_LOG (generic function with 1 method)

In [79]:
A = [4 5 ; 3 5 ; 0 -1/2];

Q, R = GS_MOD_LOG(A)

println("\nA composição QR reduzida de \nA = $A é\n\nR = $(round.(R; digits=6)) e \nQ = $(round.(Q; digits=6))")
Q * R

Para k = 1 2 faça
	u1 = A[:, 1] => [4.0, 3.0, 0.0]
	u2 = A[:, 2] => [5.0, 5.0, -0.5]
	Para k = 1 faça:
		r[1, 1] = norm(u1) => 5.0
		w1 = u1/r[1, 1] => [0.8, 0.6, 0.0]
		Para j = 2 faça:
			R[1, 2] = w1'*u2 => 7.0
			u2 = u2 - R[1, 2]*w1 => [-0.6000000000000005, 0.7999999999999998, -0.5]

	Para k = 2 faça:
		r[2, 2] = norm(u2) => 1.1180339887498951
		w2 = u2/r[2, 2] => [-0.5366563145999499, 0.7155417527999324, -0.4472135954999578]


A composição QR reduzida de 
A = [4.0 5.0; 3.0 5.0; 0.0 -0.5] é

R = [5.0 7.0; 0.0 1.118034] e 
Q = [0.8 -0.536656; 0.6 0.715542; 0.0 -0.447214]


3×2 Matrix{Float64}:
 4.0   5.0
 3.0   5.0
 0.0  -0.5

In [80]:
A = [1 -2 1 ; 2 -1 0 ; 1 -1 1 ; -1 0 2];

Q, R = GS_MOD_LOG(A)

println("\nA composição QR reduzida de \nA = $A é\n\nR = $(round.(R; digits=6)) e \nQ = $(round.(Q; digits=6))")
Q * R

Para k = 1 2 3 faça
	u1 = A[:, 1] => [1, 2, 1, -1]
	u2 = A[:, 2] => [-2, -1, -1, 0]
	u3 = A[:, 3] => [1, 0, 1, 2]
	Para k = 1 faça:
		r[1, 1] = norm(u1) => 2.6457513110645907
		w1 = u1/r[1, 1] => [0.3779644730092272, 0.7559289460184544, 0.3779644730092272, -0.3779644730092272]
		Para j = 2 faça:
			R[1, 2] = w1'*u2 => -1.889822365046136
			u2 = u2 - R[1, 2]*w1 => [-1.2857142857142858, 0.4285714285714284, -0.2857142857142858, -0.7142857142857142]
		Para j = 3 faça:
			R[1, 3] = w1'*u3 => 0.0
			u3 = u3 - R[1, 3]*w1 => [1.0, 0.0, 1.0, 2.0]

	Para k = 2 faça:
		r[2, 2] = norm(u2) => 1.5583874449479593
		w2 = u2/r[2, 2] => [-0.8250286473253902, 0.27500954910846326, -0.1833396994056423, -0.4583492485141055]
		Para j = 3 faça:
			R[2, 3] = w2'*u3 => -1.9250668437592435
			u3 = u3 - R[2, 3]*w2 => [-0.588235294117647, 0.529411764705882, 0.6470588235294117, 1.1176470588235299]

	Para k = 3 faça:
		r[3, 3] = norm(u3) => 1.5146344928922042
		w3 = u3/r[3, 3] => [-0.3883678186903085, 0.349531036821

4×3 Matrix{Float64}:
  1.0  -2.0           1.0
  2.0  -1.0          -1.53522e-17
  1.0  -1.0           1.0
 -1.0   3.91257e-17   2.0

# PMQ / Solução de Sistemas com QR Reduzido

In [81]:
A = [4 5 ; 3 5 ; 0 -1/2];
b = [1 ; -3 ; -2];

In [83]:
Q, R = GS_MOD(A);

In [88]:
bch = Q'*b
bch = round.(bch; digits=5)

2-element Vector{Float64}:
 -1.0
 -1.78885

In [98]:
x = R\bch
x = round.(x; digits=2)

println("x = ", x)
println("\né o vetor de R² que minimiza o (PMQ)\ncom valor mínimo de ", norm(A*x - b)^2)

x = [2.04, -1.6]

é o vetor de R² que minimiza o (PMQ)
com valor mínimo de 9.8


## Função Mínimos Quadrados (QR Reduzido com GS_MOD)

In [97]:
function MinQuad(A, b)
    Q, R = GS_MOD(A);
    bch = Q'*b
    bch = round.(bch; digits=5)
    x = R\bch
    x = round.(x; digits=2)
    return x
end

MinQuad (generic function with 1 method)

In [99]:
A = [1 -2 1 ; 2 -1 0 ; 1 -1 1 ; -1 0 2];
b = [-7 ; -2 ; 7 ; -2];

x = MinQuad(A, b)
println("x = ", x)
println("\né o vetor de R² que minimiza o (PMQ)\ncom valor mínimo de ", norm(A*x - b)^2)

x = [4.0, 6.0, 2.33]

é o vetor de R² que minimiza o (PMQ)
com valor mínimo de 69.33340000000001
