In [3]:
using LinearAlgebra
using Printf

In [4]:
function GS_MOD(A)
    m, n = size(A)
    Q = zeros(m, n)
    R = zeros(n, n)

    u = []
    for i = 1:n
        push!(u, A[:, i])
    end
    for k = 1:n
        R[k, k] = norm(u[k])
        Q[:, k] = u[k]/R[k, k]
        for j = k+1:n
            R[k, j] = dot(Q[:, k], u[j])
            u[j] = u[j] - R[k, j]*Q[:, k]
        end
    end
    return Q, R
end

GS_MOD (generic function with 1 method)

In [12]:
function GS_MOD_LOG(A)
    m, n = size(A)
    Q = zeros(m, n)
    R = zeros(n, n)

    kValues = []
    print("Para k = ")
    for k = 1:n
        print(k, " ")
    end

    print("faça\n")

    u = []
    for i = 1:n
        push!(u, A[:, i])
        print("\tu$i = A[:, $i] => ", u[i], "\n")
    end


    for k = 1:n
        print("\tPara k = $k faça:\n")
        # v = u[k]
        # print("\t\tu$k = A(:, $k) => ", v, "\n")
        print("\t\tr[$k, $k] = norm(u$k) => ", round.((norm(u[k])); digits = 5), "\n")
        print("\t\tw$k = u$k/r[$k, $k] => ", round.((u[k]/norm(u[k])); digits = 5), "\n") # Q[:, k] = v/R[k, k
        R[k, k] = norm(u[k])
        Q[:, k] = u[k]/R[k, k]
        for j = k+1:n
            print("\t\tPara j = $j faça:\n")
            print("\t\t\tR[$k, $j] = w$k'*u$j => ", round.((dot(Q[:, k], u[j])); digits = 5), "\n")
            R[k, j] = dot(Q[:, k], u[j])
            print("\t\t\tu$j = u$j - R[$k, $j]*w$k => ", round.((u[j] - R[k, j]*Q[:, k]); digits = 5), "\n")
            # v = A[:, j] - R[k, j]*Q[:, k]
            # v = v - R[k, j]*Q[:, k]
            u[j] = u[j] - R[k, j]*Q[:, k]
        end
        print("\n")
    end
    return Q, R
end

GS_MOD_LOG (generic function with 1 method)

In [13]:
A = [4 5 ; 3 5 ; 0 -1/2];

Q, R = GS_MOD_LOG(A)

println("\nA composição QR reduzida de \nA = $A é\n\nR = $(round.(R; digits=6)) e \nQ = $(round.(Q; digits=6))")
Q * R

Para k = 1 2 faça
	u1 = A[:, 1] => [4.0, 3.0, 0.0]
	u2 = A[:, 2] => [5.0, 5.0, -0.5]
	Para k = 1 faça:
		r[1, 1] = norm(u1) => 5.0
		w1 = u1/r[1, 1] => [0.8, 0.6, 0.0]
		Para j = 2 faça:
			R[1, 2] = w1'*u2 => 7.0
			u2 = u2 - R[1, 2]*w1 => [-0.6, 0.8, -0.5]

	Para k = 2 faça:
		r[2, 2] = norm(u2) => 1.11803
		w2 = u2/r[2, 2] => [-0.53666, 0.71554, -0.44721]


A composição QR reduzida de 
A = [4.0 5.0; 3.0 5.0; 0.0 -0.5] é

R = [5.0 7.0; 0.0 1.118034] e 
Q = [0.8 -0.536656; 0.6 0.715542; 0.0 -0.447214]


3×2 Matrix{Float64}:
 4.0   5.0
 3.0   5.0
 0.0  -0.5

In [15]:
A = [1 -2 1 ; 2 -1 0 ; 1 -1 1 ; -1 0 2];

Q, R = GS_MOD_LOG(A)

println("\nA composição QR reduzida de \nA = $A é\n\nR = $(round.(R; digits=6)) e \nQ = $(round.(Q; digits=6))")
Q * R

Para k = 1 2 3 faça
	u1 = A[:, 1] => [1, 2, 1, -1]
	u2 = A[:, 2] => [-2, -1, -1, 0]
	u3 = A[:, 3] => [1, 0, 1, 2]
	Para k = 1 faça:
		r[1, 1] = norm(u1) => 2.64575
		w1 = u1/r[1, 1] => [0.37796, 0.75593, 0.37796, -0.37796]
		Para j = 2 faça:
			R[1, 2] = w1'*u2 => -1.88982
			u2 = u2 - R[1, 2]*w1 => [-1.28571, 0.42857, -0.28571, -0.71429]
		Para j = 3 faça:
			R[1, 3] = w1'*u3 => 0.0
			u3 = u3 - R[1, 3]*w1 => [1.0, 0.0, 1.0, 2.0]

	Para k = 2 faça:
		r[2, 2] = norm(u2) => 1.55839
		w2 = u2/r[2, 2] => [-0.82503, 0.27501, -0.18334, -0.45835]
		Para j = 3 faça:
			R[2, 3] = w2'*u3 => -1.92507
			u3 = u3 - R[2, 3]*w2 => [-0.58824, 0.52941, 0.64706, 1.11765]

	Para k = 3 faça:
		r[3, 3] = norm(u3) => 1.51463
		w3 = u3/r[3, 3] => [-0.38837, 0.34953, 0.4272, 0.7379]


A composição QR reduzida de 
A = [1 -2 1; 2 -1 0; 1 -1 1; -1 0 2] é

R = [2.645751 -1.889822 0.0; 0.0 1.558387 -1.925067; 0.0 0.0 1.514634] e 
Q = [0.377964 -0.825029 -0.388368; 0.755929 0.27501 0.349531; 0.377964 -0.18334 0.42

4×3 Matrix{Float64}:
  1.0  -2.0           1.0
  2.0  -1.0          -1.53522e-17
  1.0  -1.0           1.0
 -1.0   3.91257e-17   2.0

# PMQ / Solução de Sistemas com QR Reduzido

In [16]:
A = [4 5 ; 3 5 ; 0 -1/2];
b = [1 ; -3 ; -2];

In [17]:
Q, R = GS_MOD(A);

In [18]:
bch = Q'*b
bch = round.(bch; digits=5)

2-element Vector{Float64}:
 -1.0
 -1.78885

In [19]:
x = R\bch
x = round.(x; digits=2)

println("x = ", x)
println("\né o vetor de R² que minimiza o (PMQ)\ncom valor mínimo de ", norm(A*x - b)^2)

x = [2.04, -1.6]

é o vetor de R² que minimiza o (PMQ)
com valor mínimo de 

9.8


## Função Mínimos Quadrados (QR Reduzido com GS_MOD)

In [20]:
function MinQuad(A, b)
    Q, R = GS_MOD(A);
    bch = Q'*b
    bch = round.(bch; digits=5)
    x = R\bch
    x = round.(x; digits=2)
    return x
end

MinQuad (generic function with 1 method)

In [21]:
A = [1 -2 1 ; 2 -1 0 ; 1 -1 1 ; -1 0 2];
b = [-7 ; -2 ; 7 ; -2];

x = MinQuad(A, b)
println("x = ", x)
println("\né o vetor de R² que minimiza o (PMQ)\ncom valor mínimo de ", norm(A*x - b)^2)

x = [4.0, 6.0, 2.33]

é o vetor de R² que minimiza o (PMQ)
com valor mínimo de 69.33340000000001
